[profile.default]
src = "solidity/contracts"
out = "out"
libs = ["lib"]
ffi = true
remappings = [
    "forge-std=solidity/lib/forge-std/src/",
    "risc0=solidity/lib/risc0-ethereum/contracts/src/",
    "openzeppelin=solidity/lib/openzeppelin-contracts/"
]
fs_permissions = [{ access = "read-write", path = "./"}]
