[package]
name = "seq"
version = "0.1.0"
edition = "2024"

[dependencies]
sparse-merkle-tree = "0.5.0"
blake2b-rs = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8"
sha2 = "0.10"
k256 = { version = "0.13", features = ["ecdsa"] }
hex = "0.4"
